services:
  bootstraphoverdropdown:
    image: bootstraphoverdropdown
    build:
      context: crm/rukovoditel_3.6.2/template/plugins/bootstrap-hover-dropdown
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "bootstrap-hover-dropdown.js"]
